// PDF export utility using native browser capabilities
// For more advanced PDFs, consider using jspdf or @react-pdf/renderer

interface PersonaData {
  fullName: string;
  username: string;
  email: string;
  password: string;
  dateOfBirth: string;
  country: string;
  gender: string;
  phone: string;
  recoveryEmail: string;
}

interface PlatformFields {
  [platform: string]: Record<string, string>;
}

export function exportSocialPrefillToPDF(
  persona: PersonaData,
  platformFields: PlatformFields
): void {
  const printContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Social Account Credentials - ${persona.username}</title>
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 40px; color: #1a1a1a; }
        h1 { color: #0f172a; border-bottom: 2px solid #3b82f6; padding-bottom: 10px; }
        h2 { color: #334155; margin-top: 30px; }
        .persona-section { background: #f8fafc; padding: 20px; border-radius: 8px; margin: 20px 0; }
        .field { margin: 8px 0; }
        .field-label { font-weight: 600; color: #64748b; min-width: 120px; display: inline-block; }
        .field-value { color: #1e293b; }
        .platform-card { border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; margin: 16px 0; page-break-inside: avoid; }
        .platform-title { font-size: 18px; font-weight: 600; margin-bottom: 12px; color: #0f172a; }
        .footer { margin-top: 40px; text-align: center; color: #94a3b8; font-size: 12px; }
        @media print { body { margin: 20px; } }
      </style>
    </head>
    <body>
      <h1>🔐 Social Account Credentials</h1>
      <p style="color: #64748b;">Generated on ${new Date().toLocaleDateString()}</p>
      
      <div class="persona-section">
        <h2 style="margin-top: 0;">👤 Generated Persona</h2>
        <div class="field"><span class="field-label">Full Name:</span> <span class="field-value">${persona.fullName}</span></div>
        <div class="field"><span class="field-label">Username:</span> <span class="field-value">@${persona.username}</span></div>
        <div class="field"><span class="field-label">Email:</span> <span class="field-value">${persona.email}</span></div>
        <div class="field"><span class="field-label">Password:</span> <span class="field-value">${persona.password}</span></div>
        <div class="field"><span class="field-label">Date of Birth:</span> <span class="field-value">${persona.dateOfBirth}</span></div>
        <div class="field"><span class="field-label">Country:</span> <span class="field-value">${persona.country}</span></div>
        <div class="field"><span class="field-label">Phone:</span> <span class="field-value">${persona.phone}</span></div>
        <div class="field"><span class="field-label">Recovery Email:</span> <span class="field-value">${persona.recoveryEmail}</span></div>
      </div>

      <h2>📱 Platform Credentials</h2>
      ${Object.entries(platformFields).map(([platform, fields]) => `
        <div class="platform-card">
          <div class="platform-title">${platform.charAt(0).toUpperCase() + platform.slice(1)}</div>
          ${Object.entries(fields).map(([key, value]) => `
            <div class="field">
              <span class="field-label">${key}:</span> 
              <span class="field-value">${value}</span>
            </div>
          `).join('')}
        </div>
      `).join('')}

      <div class="footer">
        <p>Generated by Control Center • Keep this document secure</p>
      </div>
    </body>
    </html>
  `;

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(printContent);
    printWindow.document.close();
    printWindow.print();
  }
}

interface GeneratedSite {
  id: string;
  name: string;
  domain: string;
  description: string;
  theme: {
    primaryColor: string;
    secondaryColor: string;
    fontFamily: string;
    style: string;
  };
  features: string[];
  seoTitle: string;
  seoDescription: string;
}

export function exportMultiSiteToPDF(sites: GeneratedSite[]): void {
  const printContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Multi-Site Builder Presentation</title>
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 40px; color: #1a1a1a; }
        h1 { color: #0f172a; text-align: center; margin-bottom: 10px; }
        .subtitle { text-align: center; color: #64748b; margin-bottom: 40px; }
        .site-card { border: 1px solid #e2e8f0; border-radius: 12px; padding: 24px; margin: 24px 0; page-break-inside: avoid; }
        .site-header { display: flex; align-items: center; gap: 16px; margin-bottom: 16px; }
        .color-dot { width: 48px; height: 48px; border-radius: 8px; }
        .site-name { font-size: 24px; font-weight: 600; color: #0f172a; }
        .site-domain { color: #64748b; font-size: 14px; }
        .site-description { color: #475569; margin: 16px 0; }
        .theme-section { background: #f8fafc; padding: 16px; border-radius: 8px; margin: 16px 0; }
        .theme-colors { display: flex; gap: 8px; margin: 8px 0; }
        .theme-color { width: 24px; height: 24px; border-radius: 4px; border: 1px solid #e2e8f0; }
        .features { display: flex; flex-wrap: wrap; gap: 8px; margin: 16px 0; }
        .feature-tag { background: #e0f2fe; color: #0369a1; padding: 4px 12px; border-radius: 16px; font-size: 12px; }
        .seo-section { border-top: 1px solid #e2e8f0; padding-top: 16px; margin-top: 16px; }
        .seo-label { font-weight: 600; color: #334155; font-size: 12px; }
        .seo-value { color: #1e293b; margin-top: 4px; }
        .footer { margin-top: 40px; text-align: center; color: #94a3b8; font-size: 12px; }
        @page { margin: 1cm; }
      </style>
    </head>
    <body>
      <h1>🚀 Multi-Site Builder</h1>
      <p class="subtitle">${sites.length} Sites Generated on ${new Date().toLocaleDateString()}</p>
      
      ${sites.map((site, index) => `
        <div class="site-card">
          <div class="site-header">
            <div class="color-dot" style="background: ${site.theme.primaryColor};"></div>
            <div>
              <div class="site-name">${site.name}</div>
              <div class="site-domain">${site.domain}</div>
            </div>
          </div>
          
          <p class="site-description">${site.description}</p>
          
          <div class="theme-section">
            <strong>Theme: ${site.theme.style}</strong>
            <div class="theme-colors">
              <div class="theme-color" style="background: ${site.theme.primaryColor};" title="Primary"></div>
              <div class="theme-color" style="background: ${site.theme.secondaryColor};" title="Secondary"></div>
              <span style="margin-left: 8px; color: #64748b; font-size: 12px;">${site.theme.fontFamily}</span>
            </div>
          </div>
          
          <div class="features">
            ${site.features.map(f => `<span class="feature-tag">${f}</span>`).join('')}
          </div>
          
          <div class="seo-section">
            <div class="seo-label">SEO Title</div>
            <div class="seo-value">${site.seoTitle}</div>
            <div class="seo-label" style="margin-top: 12px;">SEO Description</div>
            <div class="seo-value">${site.seoDescription}</div>
          </div>
        </div>
      `).join('')}

      <div class="footer">
        <p>Generated by Control Center Multi-Site Builder</p>
      </div>
    </body>
    </html>
  `;

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(printContent);
    printWindow.document.close();
    printWindow.print();
  }
}
